version: '3.8'

services:
  backend:
    build: 
      context: ./be
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - MONGODB_URL=mongodb://mongodb:27017
      - MQTT_BROKER=mqtt
      - MQTT_PORT=1883
      - RASA_URL=http://rasa:5005
    volumes:
      - ./be:/app
    depends_on:
      - mongodb
      - mqtt
    networks:
      - iot-network

  frontend:
    build:
      context: ./fe
      dockerfile: Dockerfile.prd
    ports:
      - "3000:3000"
      # - "80:80"
    environment:
      - REACT_APP_API_URL=http://35.186.151.185/:8000
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    volumes:
      - ./fe:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - iot-network

  # rasa:
  #   build:
  #     context: ./rasa
  #     dockerfile: Dockerfile
  #   image: khangfu/rasa:latest
  #   ports:
  #     - "5005:5005"
  #   volumes:
  #     - rasa_models:/app/models
  #     - rasa_pip_cache:/root/.cache/pip
  #     - ./rasa:/app
  #     - ./rasa/models:/app/models
  #   command: run --enable-api --cors "*" --endpoints /app/endpoints.yml
  #   networks:
  #     - iot-network

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - iot-network

  mqtt:
    image: eclipse-mosquitto:latest
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./be/mosquitto/config:/mosquitto/config
      - ./be/mosquitto/data:/mosquitto/data
      - ./be/mosquitto/log:/mosquitto/log
    networks:
      - iot-network

  # action-server:
  #   build: ./rasa
  #   image: khangfu/action-server:latest
  #   ports:
  #     - "5055:5055"
  #   volumes:
  #     - ./rasa:/app
  #   command: run actions
  #   networks:
  #     - iot-network

networks:
  iot-network:
    driver: bridge

volumes:
  mongodb_data:
  rasa_pip_cache:
  rasa_models:
