language: "vi"

pipeline:
- name: "WhitespaceTokenizer"
- name: "LanguageModelFeaturizer"
  model_name: "bert"
  model_weights: "vinai/phobert-base"
- name: "DIETClassifier"
  epochs: 100
- name: "EntitySynonymMapper"
- name: "ResponseSelector"
  epochs: 100

policies:
- name: MemoizationPolicy
- name: RulePolicy
- name: UnexpecTEDIntentPolicy
  max_history: 5
- name: TEDPolicy
  max_history: 5
  epochs: 100
  constrain_similarities: true
assistant_id: 20250515-062317-mode-pot
